package sec.comisiones.vistas;


import sec.comisiones.dao.ChoferesDAO;
import sec.comisiones.mapeos.Usuarios;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;


public class CalendarDetalleForm extends CustomComponent {

	private static final long serialVersionUID = -7134358383230546721L;
	private VerticalLayout mainLayout;
	private Panel contenedorPanel;
	private GridLayout Form_gridLayout1;
	

	private TextField txtIdComision = new TextField();
	
	Usuarios usrLog = new Usuarios();
	
	ChoferesDAO u = new ChoferesDAO();
	
	
	
	public CalendarDetalleForm() {
		ini();
	}
	
	public CalendarDetalleForm(Usuarios usr, int idComision) {
		usrLog= usr;
		ini();
	}

	
///////////////////////////////////////////////	
///////////////////////////////////////////////
	private void ini(){
		buildMainLayout();
		setCompositionRoot(mainLayout);	
	


		Form_gridLayout1.addComponent(txtIdComision, 0, 0, 0, 0);

		
	}
	

///////////////////////////////////////////////	
///////////////////////////////////////////////

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		//  verticalSplitPanel_1
	    contenedorPanel = buildContenedorPanel();
		mainLayout.addComponent(contenedorPanel);
 
		return mainLayout;

	}

	private Panel buildContenedorPanel() {
		// common part: create layout
		Panel Form_contenedorPanel = new Panel();
		Form_contenedorPanel.setImmediate(false);
		Form_contenedorPanel.setWidth("100.0%");
		Form_contenedorPanel.setHeight("100.0%");
//		Form_contenedorPanel.setSizeFull();
		
//		Panel Form_panel0 = new Panel();
		Panel Form_panel1 = new Panel();
//		Panel Form_panel2 = new Panel();

		
//		Form_gridLayout0 = new GridLayout(6,1);
//    	Form_gridLayout0.setWidth("100.0%");
//    	Form_gridLayout0.setColumnExpandRatio(0, 0);
//    	Form_gridLayout0.setColumnExpandRatio(1, 0);
//    	Form_gridLayout0.setColumnExpandRatio(2, 0);
//    	Form_gridLayout0.setColumnExpandRatio(3, 0);
//    	Form_gridLayout0.setColumnExpandRatio(4, 0);
//    	Form_gridLayout0.setColumnExpandRatio(5, 1f);
//    	Form_gridLayout0.setSpacing(true);
    	
		Form_gridLayout1 = new GridLayout(8,8);
	    	Form_gridLayout1.setWidth("100.0%");
	    	Form_gridLayout1.setColumnExpandRatio(0, 1f);
	    	Form_gridLayout1.setColumnExpandRatio(1, 1f);
	    	Form_gridLayout1.setColumnExpandRatio(2, 1f);
	    	Form_gridLayout1.setColumnExpandRatio(3, 1f);
	    	Form_gridLayout1.setColumnExpandRatio(4, 1f);
	    	Form_gridLayout1.setColumnExpandRatio(5, 1f);
	    	Form_gridLayout1.setColumnExpandRatio(6, 1f);
	    	Form_gridLayout1.setSpacing(true);


 //   	Form_gridLayout2 = new GridLayout(1,2);
 //   	Form_gridLayout2.setWidth("100.0%");
 //   	Form_gridLayout2.setHeight(170,Unit.PIXELS);
 //   	Form_gridLayout2.setRowExpandRatio(0, 0);
 //   	Form_gridLayout2.setRowExpandRatio(1, 1f);
    	
  //  	Form_panel0.setContent(Form_gridLayout0);
	    	Form_panel1.setContent(Form_gridLayout1);
  //  	Form_panel2.setContent(Form_gridLayout2);

		// verticalLayout_1
	    	VerticalLayout Form_verticalLayout_1 = new VerticalLayout();
		Form_verticalLayout_1.setImmediate(false);
		Form_verticalLayout_1.setWidth("100.0%");
		Form_verticalLayout_1.setHeight("100.0%");
		Form_verticalLayout_1.setMargin(true);
		Form_verticalLayout_1.addComponents(Form_panel1);
		Form_verticalLayout_1.setSpacing(true);
		
		Form_contenedorPanel.setContent(Form_verticalLayout_1);
		
		return Form_contenedorPanel;
	}
	

}
