package sec.comisiones.vistas;

import java.sql.SQLException;
import java.util.function.Consumer;

import sec.comisiones.dao.AreasDAO;
import sec.comisiones.dao.CategoriasDAO;
import sec.comisiones.dao.DetalleComisionadosDAO;
import sec.comisiones.dao.EmpleadosPorProgramaDAO;
import sec.comisiones.dao.ProgramasDAO;
import sec.comisiones.mapeos.Comisiones;
import sec.comisiones.mapeos.DetalleComisionados;
import sec.comisiones.mapeos.EmpleadosPorPrograma;
import sec.comisiones.mapeos.Usuarios;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.Sizeable.Unit;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Notification.Type;



public class DetalleComisionadosForm extends CustomComponent {

	private GridLayout Form_gridLayout0;
	private GridLayout Form_gridLayout1;
	private VerticalLayout Form_mainLayout;
	private HorizontalLayout hl_GralBotones= new HorizontalLayout();
	
	private TextField txtId = new TextField("Id");
	private TextField txtIdCom = new TextField("Id Exp.");
	private TextField txtDuracion = new TextField("Duración");
	private TextField txtTipoComisionado = new TextField("TipoComisionado");
	private ComboBox cmbArea = new ComboBox("Area");
	private ComboBox cmbPrograma = new ComboBox("Programa");
	private ComboBox cmbComisionado = new ComboBox("Comisionado");
    
    
    NativeButton btnAgrega = new NativeButton("Graba");
	NativeButton btnModifica = new NativeButton("Modifica");
	NativeButton btnElimina = new NativeButton("Elimina");
	NativeButton btnCancela = new NativeButton("Cancela");
	NativeButton btnVolver = new NativeButton("");
	
	
    DetalleComisionados per = new DetalleComisionados();
	DetalleComisionadosDAO perDAO = new DetalleComisionadosDAO();
    
	AreasDAO act = new AreasDAO();
	ProgramasDAO prg = new ProgramasDAO();
	EmpleadosPorProgramaDAO emp = new EmpleadosPorProgramaDAO();
	CategoriasDAO cat = new CategoriasDAO();
	DetalleComisionados dc = new DetalleComisionados();
	EmpleadosPorPrograma e = new EmpleadosPorPrograma();
	Comisiones com = new Comisiones();
	Usuarios usrLog= new Usuarios();
	
	int idReg=0;
	String tipo="Pasajero";
	
	
	public DetalleComisionadosForm(Usuarios usr, int idReg, Comisiones com, NativeButton btnCierre ) {
		this.usrLog= usr;
		this.idReg=idReg;
		this.com=com;
		this.btnVolver=btnCierre;
		ini(); 
		
	}
	
	
	private void ini(){
		buildMainLayout();
		setCompositionRoot(Form_mainLayout);
		

		btnAgrega = new NativeButton("Graba");
		btnModifica = new NativeButton("Modifica");
		btnElimina = new NativeButton("Elimina");
		btnCancela = new NativeButton("Cancela");    	    

	    
    	cargarCombos();
    	
    	setearValidaciones();

    	definirTamañoCampos();
		
		cargarGrillas();
		

	    txtId.setEnabled(false);
	    txtIdCom.setEnabled(false);
	    txtDuracion.setEnabled(false);
	    txtTipoComisionado.setEnabled(false);
	    
    	txtId.setValue(String.valueOf(idReg));
    	txtIdCom.setValue(String.valueOf(com.getId()));
    	txtDuracion.setValue(String.valueOf(com.getDuracion()));
    	txtTipoComisionado.setValue(tipo);
		

		if(txtId.isEmpty() || txtId.getValue().equals(null) || txtId.getValue().equals("")){
			txtId.setValue("0");
	    }
		
		
		
		if (!txtId.getValue().equals("0")){
				try {
					hl_GralBotones.addComponents(btnModifica,btnElimina,btnCancela);
					per= perDAO.DevuelveDetalleComisionados(Integer.parseInt(txtId.getValue()), Integer.parseInt(txtIdCom.getValue()));
					
					txtId.setValue(String.valueOf(per.getId()));
					txtIdCom.setValue(String.valueOf(per.getIdComision()));
					
					if(per.getIdTipoComisionado()==2){
						tipo="Chofer";
						deshabilitarCampos();
					}
					txtTipoComisionado.setValue(tipo);
					
					cmbArea.setValue(per.getIdArea());
					int valorPrograma=(int)per.getIdPrograma();
					int valorSolicitante=(per.getIdEmpleado());
					
					if (cmbArea.isEmpty()){
							cmbPrograma.setContainerDataSource(prg.getAllProgramasContainer(0));
							cmbComisionado.setContainerDataSource(emp.getAllEmpleadosPorProgramaContainer(0));
						} else {
							cmbPrograma.setContainerDataSource(prg.getAllProgramasContainer((int)cmbArea.getValue()));
							cmbPrograma.setValue(valorPrograma);
							if (cmbPrograma.isEmpty()){
								cmbComisionado.setContainerDataSource(emp.getAllEmpleadosPorProgramaContainer(0));
								}else{
									cmbComisionado.setContainerDataSource(emp.getAllEmpleadosPorProgramaContainer((int)cmbPrograma.getValue()));
									cmbComisionado.setValue(emp.getIdEmpleadoPorPrograma(valorPrograma,valorSolicitante));
								}
						}
									
					//hl_GralBotones.addComponents(btnModifica,btnElimina,btnCancela);
					
					//if(txtTipoComisionado.getValue().equals("2")){
					//	deshabilitarCampos();
					//}
					
				} catch (NumberFormatException|SQLException e) {
					e.printStackTrace();
				} 
			} else {	
				hl_GralBotones.addComponents(btnAgrega,btnCancela);	
			}
			
				
		
		
		
		cmbArea.addValueChangeListener(new ValueChangeListener() {
			 public void valueChange(ValueChangeEvent event) {
				 Object selectedItemId = event.getProperty().getValue();
				 if (selectedItemId != null) {
					 cmbPrograma.setContainerDataSource(prg.getAllProgramasContainer((int)cmbArea.getValue()));
					 cmbComisionado.setContainerDataSource(emp.getAllEmpleadosPorProgramaContainer(0));
				 }
			 }
		});
	
		
		cmbPrograma.addValueChangeListener(new ValueChangeListener() {
			 public void valueChange(ValueChangeEvent event) {
				 Object selectedItemId = event.getProperty().getValue();
				 if (selectedItemId != null) {
					 cmbComisionado.setContainerDataSource(emp.getAllEmpleadosPorProgramaContainer((int)cmbPrograma.getValue()));
				 }
			 }
		});

		
		
		
		
		
		
		btnAgrega.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				if (!validarCampos()){
					Notification.show("Existen errores de validación","Revisar campos resaltados en rojo.",Type.ERROR_MESSAGE);
				} else {
						try{
							creaObjeto();
							
					//		if(perDAO.existe(Integer.parseInt(id.getValue()),Integer.parseInt(idExpediente.getValue()), dc.getIdEmpleado())>0){
							if(perDAO.existe(dc)>0){
								Notification.show("Ya se encuentra asignado el comisionado." ,Notification.Type.ERROR_MESSAGE);
							} else {
						//		perDAO.agrega(Integer.parseInt(idExpediente.getValue()),idEmp,idCat,idEsp,idProg,monto,usrLog.getId());
								perDAO.agrega(dc,usrLog.getId());
								btnVolver.click();
						//		ini(txtIdCom.getValue(),1,btnCierre);	
							}
						} catch (NumberFormatException e) {
							e.printStackTrace();
						} 
				}
			}
		});
	
				
		btnModifica.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				if (!validarCampos()){
					Notification.show("Existen errores de validación","Revisar campos resaltados en rojo.",Type.ERROR_MESSAGE);
				} else {
						try {
							creaObjeto();
							
				//			if(perDAO.existe(Integer.parseInt(id.getValue()),Integer.parseInt(idExpediente.getValue()), idEmp)>0){
							if(perDAO.existe(dc)>0){
								Notification.show("Ya se encuentra asignado el comisionado.", Notification.Type.ERROR_MESSAGE);
							} else {
				//				perDAO.modifica(Integer.parseInt(id.getValue()),idEmp,idCat,idEsp,idProg,monto,usrLog.getId());
								perDAO.modifica(dc,usrLog.getId());
								btnVolver.click();
					//			ini(txtIdCom.getValue(),1,btnCierre);
							}
						} catch (NumberFormatException e) {
							e.printStackTrace();
						} 
				}
			}
		});
	
		
		btnElimina.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				perDAO.elimina(Integer.parseInt(txtId.getValue()),usrLog.getId()); 		
				btnVolver.click();
			//	ini(txtIdCom.getValue(),1,btnCierre);
			}
		});
	
	
		btnCancela.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) { 		
				btnVolver.click();
			}
		});
	
	
		
		
	}
	
	
	private void deshabilitarCampos(){
		btnAgrega.setEnabled(false);
		btnElimina.setEnabled(false);
		btnModifica.setEnabled(false);
		cmbArea.setEnabled(false);
		cmbComisionado.setEnabled(false);
		cmbPrograma.setEnabled(false);
	}
    
	private void cargarCombos(){
    	cmbArea.setContainerDataSource(act.getAllAreasContainer());
    	cmbArea.setItemCaptionPropertyId("nombre");
    	
    	cmbPrograma.setContainerDataSource(prg.getAllProgramasContainer(0));
    	cmbPrograma.setItemCaptionPropertyId("nombre");
    	
    	cmbComisionado.setContainerDataSource(emp.getAllEmpleadosPorProgramaContainer(0));
    	cmbComisionado.setItemCaptionPropertyId("descEmpleado");
	}
	
	private void setearValidaciones(){
		
    	cmbArea.setRequired(true);
    	cmbArea.setRequiredError("Campo Obligatorio");
    	cmbArea.setValidationVisible(false);
    	
    	cmbComisionado.setRequired(true);
    	cmbComisionado.setRequiredError("Campo Obligatorio");
    	cmbComisionado.setValidationVisible(false);
    	
    	cmbPrograma.setRequired(true);
    	cmbPrograma.setRequiredError("Campo Obligatorio");
    	cmbPrograma.setValidationVisible(false);
	}

	private void definirTamañoCampos(){
		
    	cmbArea.setWidth("100.0%");	
		cmbPrograma.setWidth("100.0%");
		cmbComisionado.setWidth("100.0%");
		
	}
	
	private void cargarGrillas(){

		hl_GralBotones.setSpacing(true);
		
		Form_gridLayout0.addComponent(hl_GralBotones,0,0,5,0);
		
		Form_gridLayout1.addComponent(txtId,0,0,0,0);
		Form_gridLayout1.addComponent(txtIdCom,1,0,1,0);
		Form_gridLayout1.addComponent(txtDuracion,2,0,2,0);
		Form_gridLayout1.addComponent(txtTipoComisionado,3,0,3,0);
		
		Form_gridLayout1.addComponent(cmbArea,0,1,1,1);
		Form_gridLayout1.addComponent(cmbPrograma,2,1,3,1);
		Form_gridLayout1.addComponent(cmbComisionado,4,1,8,1);
		
	}
	
	private boolean validarCampos(){
		try{
			cmbPrograma.setValidationVisible(true);
			cmbComisionado.setValidationVisible(true);
			cmbArea.setValidationVisible(true);


			cmbComisionado.validate();
			cmbArea.validate();
			cmbPrograma.validate();

			return true;
			
		}catch(Exception e){
		//	Notification.show(" "+ e.getMessage(),Type.ERROR_MESSAGE );
			return false;
		}
		/*
		catch(NumberFormatException e){
		//	Notification.show(" "+ e.getMessage(),Type.ERROR_MESSAGE );
			return false;
			
		}catch(Validator.InvalidValueException e){
		//	Notification.show(" "+ e.getMessage(),Type.ERROR_MESSAGE );
			return false;
			
		}*/
		
	}
	
	private void creaObjeto(){
		e = new EmpleadosPorPrograma();
		e = emp.getEmpleadoDeProgramaContainer((int)cmbComisionado.getValue());
		
		float monto = cat.DevuelveCategoria(e.getIdCategoria()).getMontoProvincial();
		
		dc = new DetalleComisionados();
		dc.setId(Integer.parseInt(txtId.getValue()));
		dc.setIdComision(Integer.parseInt(txtIdCom.getValue()));
		dc.setIdEmpleado(e.getIdEmpleado());
		dc.setIdPrograma(e.getIdPrograma());
		dc.setIdCategoria(e.getIdCategoria());
		dc.setIdEspecialidad(e.getIdEspecialidad());
		// id tipo comisionado 1:empleado - 2:chofer 
		dc.setIdTipoComisionado(1);
		dc.setTiempoDuracion(Float.parseFloat(txtDuracion.getValue()));
		dc.setMontoCategoria(monto);
		dc.setViaticos(dc.calculoViaticos(monto, Float.parseFloat(txtDuracion.getValue())));
	}


///////////////////////////////////////////////	
///////////////////////////////////////////////

	@AutoGenerated
	private void buildMainLayout() {
	
		Form_mainLayout = new VerticalLayout();
		Form_mainLayout.setImmediate(false);
		Form_mainLayout.setWidth("100%");
		Form_mainLayout.setHeight("100%");
		Form_mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		
		Form_mainLayout.addComponent(buildContenedorPanel());
		
		//return Form_mainLayout_tab1;
	}


	private Panel buildContenedorPanel() {
		
		// common part: create layout
		Panel Form_contenedorPanel = new Panel();
		Form_contenedorPanel.setImmediate(false);
		Form_contenedorPanel.setWidth("100.0%");
		Form_contenedorPanel.setHeight("100.0%");
		//Form_contenedorPanel.setSizeFull();
		
		Panel Form_panel0 = new Panel();
		Panel Form_panel1 = new Panel();
		
		
		Form_gridLayout0 = new GridLayout(6,1);
		Form_gridLayout0.setWidth("100.0%");
		//  	Form_gridLayout0.setHeight(25,Unit.PIXELS);
		Form_gridLayout0.setColumnExpandRatio(0, 0);
		Form_gridLayout0.setColumnExpandRatio(1, 0);
		Form_gridLayout0.setColumnExpandRatio(2, 0);
		Form_gridLayout0.setColumnExpandRatio(3, 0);
		Form_gridLayout0.setColumnExpandRatio(4, 0);
		Form_gridLayout0.setColumnExpandRatio(5, 1f);
		
		
		
		Form_gridLayout1 = new GridLayout(9,6);
		Form_gridLayout1.setWidth("100.0%");
		Form_gridLayout1.setColumnExpandRatio(0, 0);
		Form_gridLayout1.setColumnExpandRatio(1, 0);
		Form_gridLayout1.setColumnExpandRatio(2, 1f);
		Form_gridLayout1.setColumnExpandRatio(3, 1f);
		Form_gridLayout1.setColumnExpandRatio(4, 1f);
		Form_gridLayout1.setColumnExpandRatio(5, 1f);
		Form_gridLayout1.setColumnExpandRatio(6, 1f);
		Form_gridLayout1.setColumnExpandRatio(7, 1f);
		Form_gridLayout1.setColumnExpandRatio(8, 1f);
		
		Form_gridLayout1.setSpacing(true);

		
		
		
		Form_panel0.setContent(Form_gridLayout0);
		Form_panel1.setContent(Form_gridLayout1);

		
		// verticalLayout_1
		VerticalLayout Form_verticalLayout_1 = new VerticalLayout();
		Form_verticalLayout_1.setImmediate(false);
		Form_verticalLayout_1.setWidth("100.0%");
		Form_verticalLayout_1.setHeight("100.0%");
		Form_verticalLayout_1.setMargin(true);
		Form_verticalLayout_1.addComponents(Form_panel0,Form_panel1);
		Form_verticalLayout_1.setSpacing(true);
		
		Form_contenedorPanel.setContent(Form_verticalLayout_1);
		
		return Form_contenedorPanel;
		
		// grilla >> panel >> verticalLayout >> panel	
	}


}
