package sec.comisiones.vistas;


import com.agpro.controles.LeerArchivoTXT;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

import sec.comisiones.mapeos.Usuarios;






public class ImagenForm extends CustomComponent {

	private static final long serialVersionUID = -4517077183878609727L;
	private VerticalLayout mainLayout;
	private Panel contenedorPanel;
	private VerticalLayout verticalLayout_1;

	NativeButton btnCierre = new NativeButton("Salir");
	
	
	Usuarios usrLog = new Usuarios();
	String flag = "";
	String nuevalinea = System.getProperty("line.separator"); // salto linea java
	
	
	public ImagenForm() {
		ini();  
	}
	
	public ImagenForm(Usuarios usr) {
		usrLog= usr;
		ini();   
	}

	public ImagenForm(Usuarios usr, String flag) {
		usrLog= usr;
		this.flag=flag;
		ini();   
	}
		    

	

	private void ini(){
		buildMainLayout();
		setCompositionRoot(mainLayout);	
		
// Find the application directory
//		String basepath = VaadinService.getCurrent().getBaseDirectory().getAbsolutePath();
//		FileResource resource = new FileResource(new File(basepath + "/WEB-INF/images/ImagenFondo.png"));
		
//		Image image = new Image(null, resource);
//		image.setHeight("100.0%");
//		image.setWidth("100.0%");

			
		verticalLayout_1.removeAllComponents();
//		verticalLayout_1.addComponent(image);
//		verticalLayout_1.setExpandRatio(image, 1.0f);
//		verticalLayout_1.setStyleName("fondoImagenBody");
//		verticalLayout_1.setSpacing(true);

//		@SuppressWarnings("unused")
//		CssLayout menu = new CssLayout();
		
		
		Label lbl = new Label("Sistema de Información"+ nuevalinea + new LeerArchivoTXT().DevuelveValor("sistemaNombre"));
		lbl.addStyleName("letraTituloGrande");
		
		HorizontalLayout hl=new HorizontalLayout();
		hl.setSizeFull();
		hl.addComponent(lbl);
		hl.setComponentAlignment(lbl, Alignment.MIDDLE_CENTER);
		

		verticalLayout_1.addComponent(hl);
		verticalLayout_1.setExpandRatio(hl, 1.0f);
		
		
		switch(flag) {
		 
		case "vehiculosAsignado": 
			new VehiculosAsignadosMenuForm(usrLog,"");
			break;
		 
			
			
			
			
	 	default:  
			break;
	}

		

	}

		
//////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		//  verticalSplitPanel_1
	    contenedorPanel = buildContenedorPanel();
		mainLayout.addComponent(contenedorPanel);
 
		return mainLayout;
	}

	private Panel buildContenedorPanel() {
		// common part: create layout
		contenedorPanel = new Panel();
		contenedorPanel.setImmediate(false);
		contenedorPanel.setWidth("100.0%");
		contenedorPanel.setHeight("100.0%");
		contenedorPanel.setSizeFull();
		
		// verticalLayout_1
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
//			verticalLayout_1.setMargin(true);
		contenedorPanel.setContent(verticalLayout_1);
		
		return contenedorPanel;
	}
		

	
	
	
	
	
	
	
	
}

