package sec.comisiones.vistas;

import java.text.SimpleDateFormat;
import java.util.function.Consumer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Sizeable.Unit;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

import sec.comisiones.manager.LogAuditoriaManager;
import sec.comisiones.mapeos.Usuarios;

import sec.comisiones.vistas.LogAuditoriaMenuForm.MySub;

public class LogAuditoriaMenuForm extends CustomComponent {
	private VerticalLayout mainLayout;
	private Panel contenedorPanel;
	private VerticalLayout verticalLayout_1;
	LogAuditoriaManager tblPlanificaciones = new LogAuditoriaManager();
	private Table tb;

	Usuarios usrLog = new Usuarios();
	String flag="";

    String tipo="";
	String numGuia="";
	String lugar="";
	String numResolucion="";
	String idComprador="";
	String fec1="";
	String fec2="";
	String destinoProd="";

	
	
	public LogAuditoriaMenuForm() {
		ini();  
	}
	
	public LogAuditoriaMenuForm(Usuarios usr) {
		usrLog= usr;
		ini();   
	}

	public LogAuditoriaMenuForm(Usuarios usr, String flag) {
		usrLog= usr;
		this.flag=flag;
		ini();   
	}
	    
	    


///////////////////////////////////////////////	
///////////////////////////////////////////////	
	private void ini(){
		buildMainLayout();
		setCompositionRoot(mainLayout);	

		if(flag=="carga")
		{
			UI.getCurrent().addWindow(new MySub("0",(newValue) -> { }));
		}
		
		else
		
		{
		
	    TextField txtStatus = new TextField("Status");
	    DateField fecha1 = new DateField("Fec. Desde");
	    DateField fecha2 = new DateField("Fec. Hasta");
	    TextField txtUsuario = new TextField("Usuario");
	    TextField txtAccion = new TextField("Acción");
	    TextField txtSQL= new TextField("SQL");

	    
		NativeButton btnConsulta = new NativeButton("Filtrar");


    	SimpleDateFormat dateFormat= new SimpleDateFormat("dd/MM/yyyy");
    	
		//fecha1.setValue(new Date());
		fecha1.setDateFormat("dd/MM/yyyy");
		fecha1.setResolution(Resolution.DAY);
		fecha1.setLenient(true);
		
    	
		//fecha2.setValue(new Date());
		fecha2.setDateFormat("dd/MM/yyyy");
		fecha2.setResolution(Resolution.DAY);
		fecha2.setLenient(true);
		
		
		txtStatus.setWidth(9f, Unit.EM);
		fecha1.setWidth(9f, Unit.EM);
		fecha2.setWidth(9f, Unit.EM);
		txtUsuario.setWidth(9f, Unit.EM);
		txtSQL.setWidth(9f, Unit.EM);
		txtAccion.setWidth(9f, Unit.EM);

		
		
		if (flag=="carga") {
			tipo="TODAS";
			
		} else if (flag=="cns") {
			tipo="TODAS";

		} 
			
		tb = tblPlanificaciones.cargaTabla(numGuia,lugar,destinoProd,numResolucion,fec1,fec2);

		
		HorizontalLayout hl_1= new HorizontalLayout(fecha1,fecha2,txtStatus,txtUsuario,txtAccion,txtSQL,btnConsulta);	
		verticalLayout_1.removeAllComponents();
		verticalLayout_1.addComponents(hl_1);
		verticalLayout_1.addComponent(tb);
		verticalLayout_1.setExpandRatio(tb, 1.0f);
		verticalLayout_1.setStyleName("panelNoCaption");
		verticalLayout_1.setSpacing(true);
		hl_1.setComponentAlignment(btnConsulta, Alignment.BOTTOM_RIGHT);
		hl_1.setSpacing(true);
	
		
	    btnConsulta.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				
				if (txtStatus.isEmpty()) {
					numGuia = "";
				} else { 
					numGuia = txtStatus.getValue(); 
				}
						
				if (fecha1.isEmpty()) {
					fec1 = "";
				} else {
					fec1 = dateFormat.format(fecha1.getValue());
				}
				
				if (fecha2.isEmpty()) {
					fec2 = "";
				} else {
					fec2 = dateFormat.format(fecha2.getValue());
				}

				if (txtSQL.isEmpty()) {
					numResolucion = "";
				} else { 
					numResolucion = txtSQL.getValue(); 
				}
				
				if (txtUsuario.isEmpty()) {
					lugar = "";
				} else { 
					lugar = txtUsuario.getValue(); 
				}
				
				if (txtAccion.isEmpty()) {
					destinoProd = "";
				} else { 
					destinoProd = txtAccion.getValue(); 
				}
			
				if (flag=="carga") {
					tipo="TODAS";
					
				} else if (flag=="cns") {
					tipo="TODAS";		
				}
				
				
				verticalLayout_1.removeComponent(tb);
				tb = tblPlanificaciones.cargaTabla(numGuia,lugar,destinoProd,numResolucion,fec1,fec2);
				verticalLayout_1.addComponent(tb);
				verticalLayout_1.setExpandRatio(tb, 1.0f);
				
//				tb.addValueChangeListener(new ValueChangeListener() {
//				    public void valueChange(ValueChangeEvent event) {
//				    	Object selectedItemId = event.getProperty().getValue();
//				    	if (selectedItemId != null) {
//				    		String id0=String.valueOf(tb.getItem(selectedItemId).getItemProperty("id").getValue());
//				    		UI.getCurrent().addWindow(new MySub(id0,(newValue) -> { }));
//				    	}
//				   	}
//				});
				
			}
		});	
		
		
			
//		// Handle selection change.
//		tb.addValueChangeListener(new ValueChangeListener() {
//		    public void valueChange(ValueChangeEvent event) {
//		    	Object selectedItemId = event.getProperty().getValue();
//		    	if (selectedItemId != null) {
//		    		String id0=String.valueOf(tb.getItem(selectedItemId).getItemProperty("id").getValue());
//		    		UI.getCurrent().addWindow(new MySub(id0,(newValue) -> { }));
//		    	}
//		   	}
//		});
		

		}	
	}


	
	@SuppressWarnings("serial")
	class MySub extends Window {
	    public MySub(String planificacion, Consumer<String> save) {
	    	super("Guías C");
	    	center();
	        setModal(true);
	//        setClosable(false);
	        setResizable(true);
	        this.setWidth(75, Unit.PERCENTAGE);
	        this.setHeight(84, Unit.PERCENTAGE);
	        VerticalLayout content = new VerticalLayout();
	        content.setMargin(true);
	        content.setSpacing(true);
	        
//	        GuiasCForm vusuarios6 = new GuiasCForm(usrLog,planificacion,flag);
//	        content.addComponents(vusuarios6);

	        setContent(content);
	    }
	}

	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		//  verticalSplitPanel_1
	    contenedorPanel = buildContenedorPanel();
		mainLayout.addComponent(contenedorPanel);
 
		return mainLayout;
	}

	private Panel buildContenedorPanel() {
		// common part: create layout
		contenedorPanel = new Panel();
		contenedorPanel.setImmediate(false);
		contenedorPanel.setWidth("100.0%");
		contenedorPanel.setHeight("100.0%");
		contenedorPanel.setSizeFull();
		
		// verticalLayout_1
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(true);
		contenedorPanel.setContent(verticalLayout_1);
		
		return contenedorPanel;
	}


}
