package sec.comisiones.vistas;

import java.util.function.Consumer;

import sec.comisiones.dao.MenuGeneralDAO;
import sec.comisiones.manager.MenuGeneralManager;
import sec.comisiones.mapeos.Usuarios;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.Theme;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
@Theme("comisiones")
@SuppressWarnings("serial")
public class MenuGeneralForm extends CustomComponent {


	private VerticalLayout mainLayout;
	private Panel contenedorPanel;
	private VerticalLayout verticalLayout_1;
	final MenuGeneralManager tblMenu = new MenuGeneralManager();
	private Table tb;
	Usuarios usrLog = new Usuarios();
	VentanaMenu ventMenu=null;
	

	
	public MenuGeneralForm() {
		ini();  
	}
	
	public MenuGeneralForm(Usuarios usr) {
		usrLog= usr;
		ini();   
	}

///////////////////////////////////////////////	
///////////////////////////////////////////////	
	private void ini(){
		buildMainLayout();
		setCompositionRoot(mainLayout);	

		NativeButton btnNew=new NativeButton();
		btnNew.setCaptionAsHtml(true);
		btnNew.setCaption(FontAwesome.PLUS.getHtml() + " Nuevo" );
		
    	tb = tblMenu.cargaTablaMenuGeneral();
		HorizontalLayout hl_1= new HorizontalLayout(btnNew);
		verticalLayout_1.removeAllComponents();
		verticalLayout_1.addComponent(hl_1);
		verticalLayout_1.addComponent(tb);
		verticalLayout_1.setExpandRatio(tb, 1.0f);
		verticalLayout_1.setSpacing(true);

		
		tb.addValueChangeListener(new ValueChangeListener() {
		    public void valueChange(ValueChangeEvent event) {
		    	Object selectedItemId = event.getProperty().getValue();
			    if (selectedItemId != null) {
					int id = (int) tb.getItem(tb.getValue()).getItemProperty("id").getValue();
			    	String padre = (String) tb.getItem(tb.getValue()).getItemProperty("padre").getValue();
			    	String hijo = (String) tb.getItem(tb.getValue()).getItemProperty("hijo").getValue();
			    	int orden = (int) tb.getItem(tb.getValue()).getItemProperty("orden").getValue();
		        	UI.getCurrent().addWindow(ventMenu=new VentanaMenu(id,padre,hijo,orden, (newValue) -> {}));
			    	}
			    }
		});


		
		btnNew.addClickListener((click) -> { 
			int id = 0;
	    	String padre = "";
	    	String hijo = "";
	    	int orden = 0;
	    	UI.getCurrent().addWindow(ventMenu=new VentanaMenu(id,padre,hijo,orden, (newValue) -> { }));
	        });
		
		
	}
	

	
	class VentanaMenu extends Window {

		private VerticalLayout content;
		private VerticalLayout verticalLayout_1;
//		int ventanaDetActividad_actividad;

		
	    public VentanaMenu(int id0, String padre0, String hijo0, int orden0, Consumer<String> save) {
	        super("Modifica "); // Set window caption
	        center();
	        
	        setModal(true);
	        //	setClosable(false);
	        setResizable(true);
	        this.setWidth(40, Unit.PERCENTAGE);
	        this.setHeight(22, Unit.PERCENTAGE);

	        content = new VerticalLayout();
	        content.setMargin(true);
	        content.setSpacing(true);
	        
	        verticalLayout_1= new VerticalLayout();
	        
	        MenuGeneralDAO u = new MenuGeneralDAO();
	        
    	    TextField id = new TextField("Id");
	    	TextField padre = new TextField("Padre");
	    	TextField hijo = new TextField("Hijo");
	    	TextField orden = new TextField("Orden");
	    	
    	    NativeButton btnModifica = new NativeButton("Graba");
    		NativeButton btnCancela = new NativeButton("Cancela");
    		
			id.setEnabled(false);  

			
			id.setColumns(4);
			padre.setColumns(15);
			hijo.setColumns(17);
			orden.setColumns(5);
			
			id.setValue(String.valueOf(id0));
			padre.setValue(String.valueOf(padre0));
			hijo.setValue(String.valueOf(hijo0));
			orden.setValue(String.valueOf(orden0));
			
			if (id.getValue().equals("0")) {
				btnModifica.setCaption("Agregar Menú");
			} else {
				btnModifica.setCaption("Quitar Menú");
			}
				
	    	HorizontalLayout hl_2= new HorizontalLayout(id, padre, hijo, orden);
	    	
	    	HorizontalLayout hl_1= new HorizontalLayout(btnModifica,btnCancela);
	    	verticalLayout_1.addComponents(hl_2,hl_1);
	    	
	    	hl_1.setSpacing(true);
	    	hl_2.setSpacing(true);
	    	verticalLayout_1.setSpacing(true);
	    	
	    	
			btnModifica.addClickListener(new ClickListener(){
				public void buttonClick(ClickEvent event) {
					if (id.getValue().equals("0") && !padre.getValue().equals("") && !orden.getValue().equals("0")) {
						
						u.agregaMenu(String.valueOf(padre.getValue()),String.valueOf(hijo.getValue()),Integer.parseInt(orden.getValue()), usrLog.getId());

					}else{
			//			u.eliminaARol(Integer.parseInt(id.getValue())); 
					}
					close();
					ini();	
		}
	});
	    	
	    	
			btnCancela.addClickListener(new ClickListener(){
				public void buttonClick(ClickEvent event) { 		
					close();
					ini();
		}
	});
	
			
			
			content.addComponents(verticalLayout_1);
			setContent(content);
			
			

	    }
	}
	
///////////////////////////////////////////////	
///////////////////////////////////////////////

	
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		//  verticalSplitPanel_1
	    contenedorPanel = buildContenedorPanel();
		mainLayout.addComponent(contenedorPanel);
 
		return mainLayout;
	}

	private Panel buildContenedorPanel() {
		// common part: create layout
		contenedorPanel = new Panel();
		contenedorPanel.setImmediate(false);
		contenedorPanel.setWidth("100.0%");
		contenedorPanel.setHeight("100.0%");
		contenedorPanel.setSizeFull();
		
		// verticalLayout_1
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(true);
		contenedorPanel.setContent(verticalLayout_1);
		
		return contenedorPanel;
	}


}

