package sec.comisiones.vistas;

import java.text.SimpleDateFormat;
import java.util.function.Consumer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.Sizeable.Unit;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

import sec.comisiones.manager.ComisionesManager;
import sec.comisiones.manager.ReservasManager;
import sec.comisiones.mapeos.Usuarios;
import sec.comisiones.vistas.ComisionesForm.VentanaCalendario;
import sec.comisiones.vistas.ComisionesMenuForm.MySub;



public class ReservasMenuForm extends CustomComponent {
	private VerticalLayout mainLayout;
	private Panel contenedorPanel;
	private VerticalLayout verticalLayout_1;
	ReservasManager tblPlanificaciones = new ReservasManager();
	private Table tb;

	
	Usuarios usrLog = new Usuarios();
	String flag="";
	int bandera=0;
    String tipo="";
    String numResolucion="";
	String area="";
	String programa="";
	String estado="";
	String fec="";
	String fec1="";
	String fec2="";
	boolean vencimiento=false;

	NativeButton btnCierre = new NativeButton("Salir");
	
	
	public ReservasMenuForm() {
		ini(bandera);  
	}
	
	public ReservasMenuForm(Usuarios usr) {
		usrLog= usr;
		ini(bandera);   
	}

	public ReservasMenuForm(Usuarios usr, String flag, String flag1 ) {
		usrLog= usr;
		this.flag=flag;
		this.tipo=flag1;
		ini(bandera);   
	}
	    
	    


///////////////////////////////////////////////	
///////////////////////////////////////////////	
	private void ini(int bandera){
		buildMainLayout();
		setCompositionRoot(mainLayout);	

		
		TextField txtNumCom= new TextField("Nº Comisión");
	    DateField fecha1 = new DateField("Fec. Desde");
	    DateField fecha2 = new DateField("Fec. Hasta");
	    CheckBox chkVencimiento= new CheckBox("Fec. Regreso");

	    
		NativeButton btnConsulta = new NativeButton("Filtrar");
	//    NativeButton btnCierre = new NativeButton("Salir");
	    NativeButton btnCalendario = new NativeButton("Agenda General");
	    NativeButton btnCalendario1 = new NativeButton("Agenda Vehículos");
	    NativeButton btnCalendario2 = new NativeButton("Agenda Choferes");
	    
	    NativeButton btnNew = new NativeButton("Cargar Nueva");
	    btnNew.setCaptionAsHtml(true);
		btnNew.setCaption(FontAwesome.PLUS.getHtml() + " Nuevo" );
		
		
    	SimpleDateFormat dateFormat= new SimpleDateFormat("dd/MM/yyyy");
    	
		
		//fecha1.setValue(new Date());
		fecha1.setDateFormat("dd/MM/yyyy");
		fecha1.setResolution(Resolution.DAY);
		fecha1.setLenient(true);
		
    	
		//fecha2.setValue(new Date());
		fecha2.setDateFormat("dd/MM/yyyy");
		fecha2.setResolution(Resolution.DAY);
		fecha2.setLenient(true);
		

		fecha1.setWidth(9f, Unit.EM);
		fecha2.setWidth(9f, Unit.EM);
		txtNumCom.setWidth(9f, Unit.EM);
		chkVencimiento.setWidth(5.5f, Unit.EM);

		
		if (flag=="carga") {
			btnNew.setEnabled(true);
			
		} else {
			btnNew.setEnabled(false);
			
		}
		
		
		tb = tblPlanificaciones.cargaTabla(tipo,numResolucion,fec1,fec2,vencimiento,usrLog);

		HorizontalLayout hl_1= new HorizontalLayout(btnNew,fecha1,fecha2,chkVencimiento,btnConsulta,btnCalendario,btnCalendario1,btnCalendario2);	
		verticalLayout_1.removeAllComponents();
		verticalLayout_1.addComponents(hl_1);
		verticalLayout_1.addComponent(tb);
		verticalLayout_1.setExpandRatio(tb, 1.0f);
		verticalLayout_1.setStyleName("panelNoCaption");
		verticalLayout_1.setSpacing(true);
		hl_1.setComponentAlignment(btnNew, Alignment.BOTTOM_RIGHT);
		hl_1.setComponentAlignment(btnConsulta, Alignment.BOTTOM_RIGHT);
		hl_1.setComponentAlignment(btnCalendario, Alignment.BOTTOM_RIGHT);
		hl_1.setComponentAlignment(btnCalendario1, Alignment.BOTTOM_RIGHT);
		hl_1.setComponentAlignment(btnCalendario2, Alignment.BOTTOM_RIGHT);
		hl_1.setComponentAlignment(chkVencimiento, Alignment.BOTTOM_RIGHT);
		hl_1.setSpacing(true);
	
		
		if(tipo=="vehiculos" || tipo=="choferes"){
			btnCalendario1.setVisible(false);
			btnCalendario2.setVisible(false);
		}
		
		
	    btnConsulta.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				
				
				if (txtNumCom.isEmpty()) {
					numResolucion = "";
				} else { 
					numResolucion = txtNumCom.getValue(); 
				}
					
				
				if (fecha1.isEmpty()) {
					fec1 = "";
				} else {
					fec1 = dateFormat.format(fecha1.getValue());
				}
				
				if (fecha2.isEmpty()) {
					fec2 = "";
				} else {
					fec2 = dateFormat.format(fecha2.getValue());
				}
				
				if (chkVencimiento.isEmpty()) {
					 vencimiento = false;
				} else { 
					vencimiento = chkVencimiento.getValue(); 
				}
				
				
//				if (flag=="carga") {
//					tipo="CARGA";
//					
//				} else if (flag=="cnsTodas") {
//					tipo="TODAS";
//					
//				} else if (flag=="cnsGeneradas") {
//					tipo="TODASGENERADAS";
//					
//				} 
				
				
				verticalLayout_1.removeComponent(tb);
				tb = tblPlanificaciones.cargaTabla(tipo,numResolucion,fec1,fec2,vencimiento,usrLog);
				verticalLayout_1.addComponent(tb);
				verticalLayout_1.setExpandRatio(tb, 1.0f);
				
				
				selectTabla();
				
			}
		});	
		
	
		btnNew.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().addWindow(new MySub("0","Res.",btnCierre,(newValue) -> { }));
			}});
	    
		
	    btnCalendario.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().addWindow(new ventanaCalendario(tipo,btnCierre,(newValue) -> { }));
				
			}});
	    
	    btnCalendario1.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().addWindow(new ventanaCalendario("vehiculos",btnCierre,(newValue) -> { }));
				
			}});
	    
	    btnCalendario2.addClickListener(new ClickListener(){
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().addWindow(new ventanaCalendario("choferes",btnCierre,(newValue) -> { }));
				
			}});
	    selectTabla();
		
	
	}

	public void selectTabla(){		
		tb.addValueChangeListener(new ValueChangeListener() {
		    public void valueChange(ValueChangeEvent event) {
		    	Object selectedItemId = event.getProperty().getValue();
		    	if (selectedItemId != null) {
		    		String id0=String.valueOf(tb.getItem(selectedItemId).getItemProperty("caption").getValue()).substring(6, 12);
		    		String id1=String.valueOf(tb.getItem(selectedItemId).getItemProperty("caption").getValue()).substring(0, 4);
		    		UI.getCurrent().addWindow(new MySub(id0,id1,btnCierre,(newValue) -> { }));
		    		
		    	}
		   	}
		});
		
		
		
	} 


	
//////////////////////////////////////////////////
//////////////////////////////////////////////////
	@SuppressWarnings("serial")
	class MySub extends Window {
	    public MySub(String idComision, String comRes, NativeButton btnCierre, Consumer<String> save) {
	
	    		super("");
	    		center();
	        setModal(true);
	//        setClosable(false);
	        setResizable(true);

	        VerticalLayout content = new VerticalLayout();
	        content.setMargin(true);
	        content.setSpacing(true);
	        
	        btnCierre.addClickListener(new ClickListener(){
				public void buttonClick(ClickEvent event) {
					close();
					ini(1);
				}
			});

	        if(comRes.equals("Com.")){
	        		this.setCaption("Detalle Comisión");
	        		this.setWidth(120, Unit.EM);
	        		ComisionesForm vusuarios6=new ComisionesForm(usrLog,idComision,flag,btnCierre);
	        		content.addComponents(vusuarios6);

	        }else if(comRes.equals("Res.")) {
	        		this.setCaption("Reserva Libre");
	        		this.setWidth(60, Unit.EM);
	        		ReservasForm vusuarios6=new ReservasForm(usrLog,idComision,flag,btnCierre);
	        		content.addComponents(vusuarios6);
	        	
	        }
	        

	        setContent(content);
	    }
	}

	
//////////////////////////////////////////////////
//////////////////////////////////////////////////
@SuppressWarnings("serial")
	class ventanaCalendario extends Window {
	    public ventanaCalendario(String tipoEvento, NativeButton btnCierre, Consumer<String> save) {
	
	    	super("Calendario Comisiones");
	    	center();
	        setModal(true);
	//        setClosable(false);
	        setResizable(true);
	        this.setWidth(90, Unit.PERCENTAGE);
//	        this.setHeight(98, Unit.PERCENTAGE);
	        VerticalLayout content = new VerticalLayout();
	        content.setMargin(true);
	        content.setSpacing(true);
	        
//	        btnCierre.addClickListener(new ClickListener(){
//				public void buttonClick(ClickEvent event) {
//					close();
//					ini(1);
//				}
//			});
	        

	        
	        CalendarForm vusuarios6 = new CalendarForm(tipoEvento);
	        content.addComponents(vusuarios6);

	        

	        setContent(content);
	    }
	}

	
//////////////////////////////////////////////////
//////////////////////////////////////////////////
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setSizeFull();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		//  verticalSplitPanel_1
	    contenedorPanel = buildContenedorPanel();
		mainLayout.addComponent(contenedorPanel);
 
		return mainLayout;
	}

	private Panel buildContenedorPanel() {
		// common part: create layout
		contenedorPanel = new Panel();
		contenedorPanel.setImmediate(false);
		contenedorPanel.setWidth("100.0%");
		contenedorPanel.setHeight("100.0%");
		contenedorPanel.setSizeFull();
		
		// verticalLayout_1
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(true);
		contenedorPanel.setContent(verticalLayout_1);
		
		return contenedorPanel;
	}


}
